// Sample data for coffee ecommerce app
//import bcrypt from 'bcrypt'

export const products = [
  {
    productName: "Ethiopian Yirgacheffe",
    productType: "Single Origin",
    roastLevel: "Light",
    description: "Bright and floral with notes of citrus and tea-like body.",
    imgUrl: "/coffee-1.jpg",
    farmName: "Kochere Washing Station",
    farmRegion: "Yirgacheffe",
    farmCountry: "Ethiopia",
    farmAltitude: "1,800-2,000m",
    producer: "Local Smallholders",
    varietal: "Heirloom Ethiopian",
    harvestSeason: "October - December",
    farmingPractice: ["Organic", "Shade Grown"],
    farmStory: "Grown by smallholder farmers in the birthplace of coffee.",
    processingMethod: "Washed",
    roastDate: "2024-01-15",
    roastProfile: "Light City",
    tastingNotes: ["Lemon", "Floral", "Black Tea"],
    brewingRecommendation: ["Pour Over", "V60", "Chemex", "French Press"],
    weight: [250, 500, 1000],
    price: [18.99, 34.99, 64.99],
    stockQuantity: 50
  },
  {
    productName: "Colombian Supremo",
    productType: "Single Origin",
    roastLevel: "Medium",
    description: "Balanced, sweet, and nutty with a smooth finish.",
    imgUrl: "/coffee-2.jpg",
    farmName: "Finca La Esperanza",
    farmRegion: "Huila",
    farmCountry: "Colombia",
    farmAltitude: "1,600m",
    producer: "Juan Valdez",
    varietal: "Caturra",
    harvestSeason: "May - July",
    farmingPractice: ["Rainforest Alliance"],
    farmStory: "Family-owned farm with sustainable practices.",
    processingMethod: "Washed",
    roastDate: "2024-02-10",
    roastProfile: "Medium",
    tastingNotes: ["Caramel", "Hazelnut", "Red Apple"],
    brewingRecommendation: ["Drip", "Aeropress"],
    weight: [250, 500, 1000],
    price: [16.99, 31.99, 59.99],
    stockQuantity: 40
  },
  {
    productName: "Kenya AA",
    productType: "Single Origin",
    roastLevel: "Medium-Light",
    description: "Juicy acidity, berry flavors, and a wine-like finish.",
    imgUrl: "/coffee-3.jpg",
    farmName: "Nyeri Hill Estate",
    farmRegion: "Nyeri",
    farmCountry: "Kenya",
    farmAltitude: "1,900m",
    producer: "Cooperative",
    varietal: "SL28, SL34",
    harvestSeason: "June - August",
    farmingPractice: ["Direct Trade"],
    farmStory: "Grown on volcanic soil for unique flavor.",
    processingMethod: "Washed",
    roastDate: "2024-03-05",
    roastProfile: "Medium-Light",
    tastingNotes: ["Blackcurrant", "Grapefruit", "Winey"],
    brewingRecommendation: ["Pour Over", "Cold Brew"],
    weight: [250, 500, 1000],
    price: [19.99, 36.99, 69.99],
    stockQuantity: 35
  },
  {
    productName: "Sumatra Mandheling",
    productType: "Single Origin",
    roastLevel: "Dark",
    description: "Earthy, full-bodied, with notes of chocolate and spice.",
    imgUrl: "/coffee-4.jpg",
    farmName: "Lintong Estate",
    farmRegion: "Lintong",
    farmCountry: "Indonesia",
    farmAltitude: "1,400m",
    producer: "Smallholders",
    varietal: "Typica",
    harvestSeason: "September - November",
    farmingPractice: ["Organic"],
    farmStory: "Traditional wet-hulled processing for deep flavors.",
    processingMethod: "Wet-Hulled",
    roastDate: "2024-01-25",
    roastProfile: "French Roast",
    tastingNotes: ["Dark Chocolate", "Spice", "Earthy"],
    brewingRecommendation: ["Espresso", "French Press"],
    weight: [250, 500, 1000],
    price: [17.99, 33.99, 62.99],
    stockQuantity: 30
  },
  {
    productName: "Guatemala Antigua",
    productType: "Single Origin",
    roastLevel: "Medium",
    description: "Sweet, chocolatey, with a hint of spice and citrus.",
    imgUrl: "/coffee-5.jpg",
    farmName: "Finca El Pilar",
    farmRegion: "Antigua",
    farmCountry: "Guatemala",
    farmAltitude: "1,500m",
    producer: "Maria Zelaya",
    varietal: "Bourbon",
    harvestSeason: "January - March",
    farmingPractice: ["Rainforest Alliance"],
    farmStory: "Shade-grown coffee from volcanic soils.",
    processingMethod: "Washed",
    roastDate: "2024-02-20",
    roastProfile: "Medium",
    tastingNotes: ["Chocolate", "Orange", "Cinnamon"],
    brewingRecommendation: ["Drip", "Pour Over"],
    weight: [250, 500, 1000],
    price: [17.49, 32.99, 61.99],
    stockQuantity: 45
  },
  {
    productName: "Brazil Santos",
    productType: "Single Origin",
    roastLevel: "Medium",
    description: "Nutty, low acidity, and smooth body.",
    imgUrl: "/coffee-6.jpg",
    farmName: "Fazenda Primavera",
    farmRegion: "Minas Gerais",
    farmCountry: "Brazil",
    farmAltitude: "1,100m",
    producer: "Carlos Souza",
    varietal: "Mundo Novo",
    harvestSeason: "June - September",
    farmingPractice: ["Direct Trade"],
    farmStory: "Classic Brazilian coffee from a family farm.",
    processingMethod: "Natural",
    roastDate: "2024-03-15",
    roastProfile: "Medium",
    tastingNotes: ["Peanut", "Milk Chocolate", "Sweet"],
    brewingRecommendation: ["Espresso", "Drip"],
    weight: [250, 500, 1000],
    price: [15.99, 29.99, 54.99],
    stockQuantity: 60
  },
  {
    productName: "Costa Rica Tarrazú",
    productType: "Single Origin",
    roastLevel: "Medium-Light",
    description: "Bright acidity, honey sweetness, and citrus notes.",
    imgUrl: "/coffee-7.jpg",
    farmName: "La Pastora",
    farmRegion: "Tarrazú",
    farmCountry: "Costa Rica",
    farmAltitude: "1,600m",
    producer: "Cooperative",
    varietal: "Caturra, Catuai",
    harvestSeason: "December - March",
    farmingPractice: ["Sustainable"],
    farmStory: "Mountain-grown coffee with unique microclimate.",
    processingMethod: "Washed",
    roastDate: "2024-02-28",
    roastProfile: "Medium-Light",
    tastingNotes: ["Honey", "Citrus", "Almond"],
    brewingRecommendation: ["Pour Over", "Aeropress"],
    weight: [250, 500, 1000],
    price: [18.49, 34.49, 65.49],
    stockQuantity: 38
  },
  {
    productName: "Honduras Marcala",
    productType: "Single Origin",
    roastLevel: "Medium",
    description: "Sweet, balanced, with notes of caramel and stone fruit.",
    imgUrl: "/coffee-8.jpg",
    farmName: "Finca Liquidámbar",
    farmRegion: "Marcala",
    farmCountry: "Honduras",
    farmAltitude: "1,350m",
    producer: "Women Producers",
    varietal: "Pacas",
    harvestSeason: "November - February",
    farmingPractice: ["Organic", "Fair Trade"],
    farmStory: "Empowering women in coffee farming.",
    processingMethod: "Washed",
    roastDate: "2024-03-10",
    roastProfile: "Medium",
    tastingNotes: ["Caramel", "Peach", "Brown Sugar"],
    brewingRecommendation: ["Drip", "French Press"],
    weight: [250, 500, 1000],
    price: [16.49, 30.99, 58.99],
    stockQuantity: 42
  },
  {
    productName: "Peru Cajamarca",
    productType: "Single Origin",
    roastLevel: "Medium",
    description: "Mild acidity, chocolatey, with floral undertones.",
    imgUrl: "/coffee-9.jpg",
    farmName: "Finca Churupampa",
    farmRegion: "Cajamarca",
    farmCountry: "Peru",
    farmAltitude: "1,700m",
    producer: "Churupampa Family",
    varietal: "Typica, Caturra",
    harvestSeason: "April - July",
    farmingPractice: ["Organic"],
    farmStory: "Family-run farm with a focus on quality.",
    processingMethod: "Washed",
    roastDate: "2024-03-18",
    roastProfile: "Medium",
    tastingNotes: ["Milk Chocolate", "Floral", "Mild"],
    brewingRecommendation: ["Pour Over", "Drip"],
    weight: [250, 500, 1000],
    price: [17.29, 31.99, 60.99],
    stockQuantity: 36
  },
  {
    productName: "Mexico Chiapas",
    productType: "Single Origin",
    roastLevel: "Medium-Dark",
    description: "Rich, chocolatey, with a hint of spice.",
    imgUrl: "/coffee-10.jpg",
    farmName: "Finca Santa Cruz",
    farmRegion: "Chiapas",
    farmCountry: "Mexico",
    farmAltitude: "1,200m",
    producer: "Santa Cruz Family",
    varietal: "Bourbon, Typica",
    harvestSeason: "December - March",
    farmingPractice: ["Organic", "Fair Trade"],
    farmStory: "Sustainable coffee from the highlands.",
    processingMethod: "Washed",
    roastDate: "2024-02-18",
    roastProfile: "Medium-Dark",
    tastingNotes: ["Dark Chocolate", "Spice", "Nutty"],
    brewingRecommendation: ["Espresso", "French Press"],
    weight: [250, 500, 1000],
    price: [16.79, 32.49, 61.49],
    stockQuantity: 33
  },
  {
    productName: "Panama Geisha",
    productType: "Single Origin",
    roastLevel: "Light",
    description: "Delicate, floral, and tea-like with jasmine aroma.",
    imgUrl: "/coffee-11.jpg",
    farmName: "Hacienda La Esmeralda",
    farmRegion: "Boquete",
    farmCountry: "Panama",
    farmAltitude: "1,700m",
    producer: "Peterson Family",
    varietal: "Geisha",
    harvestSeason: "January - March",
    farmingPractice: ["Direct Trade"],
    farmStory: "World-renowned Geisha variety from Panama.",
    processingMethod: "Washed",
    roastDate: "2024-03-22",
    roastProfile: "Light",
    tastingNotes: ["Jasmine", "Bergamot", "Tea"],
    brewingRecommendation: ["Pour Over", "Chemex"],
    weight: [125, 250],
    price: [29.99, 54.99],
    stockQuantity: 12
  },
  {
    productName: "Rwanda Nyamasheke",
    productType: "Single Origin",
    roastLevel: "Medium-Light",
    description: "Sweet, juicy, with notes of red fruit and honey.",
    imgUrl: "/coffee-12.jpg",
    farmName: "Nyamasheke Cooperative",
    farmRegion: "Nyamasheke",
    farmCountry: "Rwanda",
    farmAltitude: "1,800m",
    producer: "Cooperative",
    varietal: "Bourbon",
    harvestSeason: "March - June",
    farmingPractice: ["Fair Trade"],
    farmStory: "Empowering local farmers through cooperatives.",
    processingMethod: "Washed",
    roastDate: "2024-03-12",
    roastProfile: "Medium-Light",
    tastingNotes: ["Red Fruit", "Honey", "Juicy"],
    brewingRecommendation: ["Pour Over", "Aeropress"],
    weight: [250, 500],
    price: [18.99, 34.99],
    stockQuantity: 20
  },
  {
    productName: "Tanzania Peaberry",
    productType: "Single Origin",
    roastLevel: "Medium",
    description: "Bright acidity, medium body, and fruity notes.",
    imgUrl: "/coffee-13.jpg",
    farmName: "Kilimanjaro Estate",
    farmRegion: "Kilimanjaro",
    farmCountry: "Tanzania",
    farmAltitude: "1,600m",
    producer: "Smallholders",
    varietal: "Bourbon, Kent",
    harvestSeason: "July - October",
    farmingPractice: ["Sustainable"],
    farmStory: "Unique peaberry beans from the slopes of Kilimanjaro.",
    processingMethod: "Washed",
    roastDate: "2024-03-08",
    roastProfile: "Medium",
    tastingNotes: ["Fruity", "Bright", "Medium Body"],
    brewingRecommendation: ["Drip", "Pour Over"],
    weight: [250, 500, 1000],
    price: [17.99, 33.99, 62.99],
    stockQuantity: 28
  },
  {
    productName: "India Monsooned Malabar",
    productType: "Single Origin",
    roastLevel: "Dark",
    description: "Low acidity, heavy body, and earthy flavors.",
    imgUrl: "/coffee-14.jpg",
    farmName: "Malabar Coast",
    farmRegion: "Karnataka",
    farmCountry: "India",
    farmAltitude: "1,200m",
    producer: "Local Estates",
    varietal: "Kent, S795",
    harvestSeason: "June - September",
    farmingPractice: ["Monsooned"],
    farmStory: "Unique monsooning process for mellow flavors.",
    processingMethod: "Monsooned",
    roastDate: "2024-02-25",
    roastProfile: "Dark",
    tastingNotes: ["Earthy", "Heavy Body", "Low Acidity"],
    brewingRecommendation: ["Espresso", "French Press"],
    weight: [250, 500, 1000],
    price: [16.99, 31.99, 59.99],
    stockQuantity: 22
  },
  {
    productName: "Papua New Guinea Sigri",
    productType: "Single Origin",
    roastLevel: "Medium",
    description: "Sweet, clean, with tropical fruit and floral notes.",
    imgUrl: "/coffee-15.jpg",
    farmName: "Sigri Estate",
    farmRegion: "Wahgi Valley",
    farmCountry: "Papua New Guinea",
    farmAltitude: "1,600m",
    producer: "Sigri Estate",
    varietal: "Typica, Bourbon",
    harvestSeason: "April - September",
    farmingPractice: ["Rainforest Alliance"],
    farmStory: "Estate-grown coffee with strict quality control.",
    processingMethod: "Washed",
    roastDate: "2024-03-02",
    roastProfile: "Medium",
    tastingNotes: ["Tropical Fruit", "Floral", "Sweet"],
    brewingRecommendation: ["Pour Over", "Drip"],
    weight: [250, 500, 1000],
    price: [18.49, 34.49, 65.49],
    stockQuantity: 18
  },
  {
    productName: "El Salvador Pacamara",
    productType: "Single Origin",
    roastLevel: "Medium-Light",
    description: "Complex, fruity, with a creamy body.",
    imgUrl: "/coffee-16.jpg",
    farmName: "Finca Los Pirineos",
    farmRegion: "Usulután",
    farmCountry: "El Salvador",
    farmAltitude: "1,400m",
    producer: "Gilberto Baraona",
    varietal: "Pacamara",
    harvestSeason: "January - March",
    farmingPractice: ["Direct Trade"],
    farmStory: "Award-winning farm with unique varietals.",
    processingMethod: "Washed",
    roastDate: "2024-03-20",
    roastProfile: "Medium-Light",
    tastingNotes: ["Berry", "Creamy", "Complex"],
    brewingRecommendation: ["Pour Over", "Aeropress"],
    weight: [250, 500, 1000],
    price: [19.49, 35.99, 68.99],
    stockQuantity: 14
  },
  {
    productName: "Nicaragua Jinotega",
    productType: "Single Origin",
    roastLevel: "Medium",
    description: "Sweet, balanced, with notes of cocoa and citrus.",
    imgUrl: "/coffee-17.jpg",
    farmName: "Finca La Bastilla",
    farmRegion: "Jinotega",
    farmCountry: "Nicaragua",
    farmAltitude: "1,300m",
    producer: "La Bastilla Estate",
    varietal: "Caturra, Catuai",
    harvestSeason: "December - March",
    farmingPractice: ["Rainforest Alliance"],
    farmStory: "Estate-grown coffee with a focus on sustainability.",
    processingMethod: "Washed",
    roastDate: "2024-03-14",
    roastProfile: "Medium",
    tastingNotes: ["Cocoa", "Citrus", "Sweet"],
    brewingRecommendation: ["Drip", "French Press"],
    weight: [250, 500, 1000],
    price: [16.99, 31.99, 59.99],
    stockQuantity: 25
  },
  {
    productName: "Burundi Kayanza",
    productType: "Single Origin",
    roastLevel: "Light",
    description: "Bright, juicy, with notes of red fruit and floral.",
    imgUrl: "/coffee-18.jpg",
    farmName: "Kayanza Washing Station",
    farmRegion: "Kayanza",
    farmCountry: "Burundi",
    farmAltitude: "1,800m",
    producer: "Cooperative",
    varietal: "Bourbon",
    harvestSeason: "April - July",
    farmingPractice: ["Fair Trade"],
    farmStory: "Community-focused washing station.",
    processingMethod: "Washed",
    roastDate: "2024-03-06",
    roastProfile: "Light",
    tastingNotes: ["Red Fruit", "Floral", "Juicy"],
    brewingRecommendation: ["Pour Over", "Aeropress"],
    weight: [250, 500, 1000],
    price: [18.99, 34.99, 64.99],
    stockQuantity: 19
  },
  {
    productName: "Yemen Mocha Matari",
    productType: "Single Origin",
    roastLevel: "Medium-Dark",
    description: "Winey, spicy, with chocolate and dried fruit notes.",
    imgUrl: "/coffee-19.jpg",
    farmName: "Matari Region",
    farmRegion: "Sa'dah",
    farmCountry: "Yemen",
    farmAltitude: "1,900m",
    producer: "Smallholders",
    varietal: "Typica",
    harvestSeason: "October - January",
    farmingPractice: ["Traditional"],
    farmStory: "Ancient coffee traditions from Yemen.",
    processingMethod: "Natural",
    roastDate: "2024-02-12",
    roastProfile: "Medium-Dark",
    tastingNotes: ["Chocolate", "Winey", "Dried Fruit"],
    brewingRecommendation: ["Espresso", "Pour Over"],
    weight: [250, 500],
    price: [24.99, 46.99],
    stockQuantity: 10
  },
  {
    productName: "House Blend",
    productType: "Blend",
    roastLevel: "Medium",
    description: "Smooth, balanced, and versatile for any brew method.",
    imgUrl: "/coffee-20.jpg",
    farmName: "Various",
    farmRegion: "Blend",
    farmCountry: "Multiple",
    farmAltitude: "",
    producer: "",
    varietal: "Blend",
    harvestSeason: "",
    farmingPractice: ["Sustainable"],
    farmStory: "A carefully crafted blend for everyday enjoyment.",
    processingMethod: "Washed & Natural",
    roastDate: "2024-03-25",
    roastProfile: "Medium",
    tastingNotes: ["Balanced", "Smooth", "Sweet"],
    brewingRecommendation: ["Drip", "Espresso", "French Press"],
    weight: [250, 500, 1000],
    price: [15.99, 29.99, 54.99],
    stockQuantity: 100
  }
];

// Users data with hashed passwords
// export const users = [
//   {
//     id: '1',
//     name: 'Coffee Admin',
//     email: 'admin@coffeeshop.com',
//     password: '$2b$10$K7L/8Y1t85D1yGmmi5rYiOeRhQy6RXtb5/FjwR6ais61jH.nja5S6', // password123
//   },
// ];

// Orders data
// export const orders = [
//   {
//     id: '1',
//     customerId: '1',
//     amount: 1899,
//     status: orders
//     date: new Date('2024-01-15'),
//   },
// ];
